### ISSUE TITLE
Style cleanup?

### ISSUE THREAD

**Issue by metasoarous** [Hendekagon/lein-clique#4]
I'd love to help with this project, but it would be nice if the style was a little more consistent with that observed in the rest of the Clojure community (I think [bbatsov's guide](https://github.com/bbatsov/clojure-style-guide) is pretty representative). I suggest this because:

1) I'm a bit OCD when it comes to styling; it helps me visualize things...
2) You mentioned in your Clojure Google Group announcement that you were pretty new to Clojure when you did this, so maybe you weren't really familiar with the usual styling yet.

I've forked the repo and made some changes along these lines, and could contribute some other (as I see it) cleanups if you're amenable. Let me know if you'd like me to do a pull request.

**Comment by Hendekagon** [comment]
yes absolutely, this code is old & naive
